export enum sceneNames {
    Butterchurn = 'Butterchurn',
    SunFlower = 'SunFlower',
    FrostFire = 'FrostFire',
    SynthBars = 'SynthBars',
    DancingHorizon = 'DancingHorizon',
    DancingCubes3DSinus = 'DancingCubes3DSinus',
    WormScene = 'WormScene',
    Dancing3DCubes = 'Dancing3DCubes',
    RoundSpectrum = 'RoundSpectrum',
    SeventiesScene = 'SeventiesScene',
    ParticleCircle = 'ParticleCircle',
    PsychedelicCube = 'PsychedelicCube',
    AudioTerrain = 'AudioTerrain',
    CircleBurst = 'CircleBurst',
    PaintSplash = 'PaintSplash',
    HexagonPulse = 'HexagonPulse',
    OrbitalRing = 'OrbitalRing',
    NeuralWeb = 'NeuralWeb',
    FloatingCubes = 'FloatingCubes',
    ChromaWave = 'ChromaWave',
    CosmicAurora = 'CosmicAurora',
}
